### ISSUE TITLE
zsh: command not found: fresh

### ISSUE THREAD

**Issue by AtharvaThorve** [gravityblast/fresh#110]
I am using WSL+ZSH on my windows setup but when I try to execute command `fresh` after executing `go get github.com/pilu/fresh` I get the error `zsh: command not found: fresh`. <br>
When I directly use windows powershell then it works fine but when using WSL leads to the above error.<br>
This is my `go env`:
```shell
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build770270849=/tmp/go-build -gno-record-gcc-switches"
```
What should I do to resolve this error?

**Comment by Uttammgr** [comment]
@AtharvaThorve  i had similar issue but i'm one mac, the way i solved it by fixing path

 * first i made seperate folder for getting folder for go get library so i named golib 
 * then set it to go path where following should resemble 
>  refer to following example 
```zsh
go_sandbox
├── bin
├── pkg
└── src
    └── github.com
        └── Uttammgr
```
* i think you can do similar by adding following after setting up properly

```zsh
export GOPATH="$HOME/golib"
export PATH="$PATH:$GOPATH/bin"
export GOPATH="$GOPATH:$HOME/Documents/code_sandbox/go_sandbox"
````

**Comment by PSalant726** [comment]
@AtharvaThorve The `go env GOPATH` variable is set when the language is installed, but `$GOPATH` is not. If you want to install global package binaries, you need to set `$GOPATH` and add `$GOPATH/bin` to your `$PATH` in your `.zhsrc` file. Then, you can `go get {{ some package }}` **outside of a module directory**, and you'll be able to run the binary globally.
